export const SET_ACTIVE_PANEL = "SET_ACTIVE_PANEL";
export const SET_ITEM_DATA = "SET_ITEM_DATA";
export const SET_CATEGORY_INDEX = "SET_CATEGORY_INDEX";
export const SET_CATEGORY = "SET_CATEGORY";
export const ADD_TO_CART = "ADD_TO_CART";